### ISSUE TITLE
.local restriction

### ISSUE THREAD

**Issue by SepiDre** [lociii/homeassistant-overwolf-status#1]
Hi lociii
Your app sound awesome and I want to use it.
Unfortunately, I cannot add my Home Assistant because it is neither a casa HA nor a .local domain.
I tried to add my domain in the installed manifest but it will be overwritten after each restart.

Can you please remove the "matches"?

I think the Home Assistant community is tecki enough to know how to reach their system.
By the way - .local is a bad naming decision. If there are multiple apple devices in this domain, they may be feeling slow due to the bonjour requests to .local :-)

Thanks!

**Comment by lociii** [comment]
Hey SepiDre,

great that you like the app.

The issue here is not that I don't trust the Home Assistant community to know how to enter their instance URL but that Overwolf is limiting which external URLs an app is allowed to connect to.

See `externally_connectable` on https://overwolf.github.io/api/manifest

Which URL are you using. Feel free to anonymize parts of it.

Best.

**Comment by lociii** [comment]
> By the way - .local is a bad naming decision. If there are multiple apple devices in this domain, they may be feeling slow due to the bonjour requests to .local :-)

homeassistant.local is the default name of a new HA installation.

**Comment by SepiDre** [comment]
Ah, I never used the default naming 😅
My domain would be https://*.zone

**Comment by lociii** [comment]
> Ah, I never used the default naming 😅
> My domain would be https://*.zone

As this is a regular TLD, whitelisting it won't be possible according to the Overwolf rules.
Using the public address also usually means that all requests would be routed through the public internet.

Assuming that your gaming PC is on the same network as your Home Assistant server, it would make most sense to send these events locally (depending on the game there will be a lot (!!!) events).

Check the network settings to define a local name for your instance.  
![Screenshot_20230204-130526~2.png](https://user-images.githubusercontent.com/366967/216766928-06e95d0e-f392-41a4-b510-336c93b65f2c.png)

**Comment by SepiDre** [comment]
Hi lociii
I am a little bit lost. I tried everything so fahr to get the Webhook working with the local naming.
I added the name to my hosts file and can connect it through http://assi-pi.local:8123 (my name) but the webhook iss only reachable through the https address or http://localip:8123.

Am I too stupid?

**Comment by SepiDre** [comment]
I am too stupid - with the ip, I was logged in. With the new name not.
