### ISSUE TITLE
Where do i find the "webhook URL" or the "hook id" exactly?

### ISSUE THREAD

**Issue by Tony2407** [lociii/homeassistant-overwolf-status#3]
Hi everyone!
I've installed HACS on my Home Assistant and with HACS I  installed the integration "Overwolf Webhook".
I'm now on step 3 of the Github documenation. But i can't find any Webhook URLs.

Do I need the Home Assistant Cloud, which costs money, so that I can get a webhook URL or can I do this for free in another way?
The goal is to display news/statistics etc. from games like CS:GO or League of Legends on my Echo Show.

If anyone has an idea, I would be very happy to hear from you here or in a direct message.

Kind regards
Toni

**Comment by lociii** [comment]
Please follow up on https://community.home-assistant.io/t/overwolf-game-event-integration/528083/4 so that other community members can take part of the discussion. I'd close this one here as it's not an issue with the integration. Thanks.
