### ISSUE TITLE
Incompatibility with Home Assistant 2024.9

### ISSUE THREAD

**Issue by ckarrie** [lociii/homeassistant-overwolf-status#4]
Hi, just read my HomeAssistant 2024.06 Logs and got this message:

Detected that custom integration 'overwolfstatus' accesses `hass.components.webhook`. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from webhook directly at `custom_components/overwolfstatus/__init__.py`, line 27: `hass.components.webhook.async_register(`

Thank you!

**Comment by lociii** [comment]
Thanks for reporting. `1.0.2` fixes the import deprecation.

**Comment by ckarrie** [comment]
Thank you
